apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runlore.fullname" . }}-config
  labels:
    {{- include "runlore.labels" . | nindent 4 }}
data:
  runlore.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
