{{- if ne .Values.workloadKind "StatefulSet" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runlore.fullname" . }}
  labels:
    {{- include "runlore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      {{- include "runlore.selectorLabels" . | nindent 6 }}
  template:
    {{- include "runlore.podTemplate" . | nindent 4 }}
{{- end }}
